name: ethiopian_bank_tracker
description: A Flutter app for tracking Ethiopian bank accounts and transactions.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  permission_handler: ^10.2.0
  flutter_sms_inbox: ^1.0.1
  intl: ^0.19.0
  provider: ^6.0.3
  flutter_svg: ^1.1.6
  flutter_carousel_widget: ^2.2.0
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
